### PR TITLE
Point the "Show versions" button to an URL that *actually* has a listing of previous versions

### PR DESCRIPTION
**Pull request by squarefractal**

### CODE REVIEW

**Comment by wolfbeast** [comment]
Since when is "Show versions" equal to "release notes"?

**Comment by squarefractal** [comment]
linux.palemoon.org isn't appropriate either :wink:

Previously, this link used to point at http://sourceforge.net/projects/pm4linux/files; however, with the move to linux.palemoon.org there's no equivalent -- http://linux.palemoon.org/files also has directory listing blocked, so this is the only actual listing an user could use to locate previous versions, if necessary.

**Comment by wolfbeast** [comment]
It may need some rethinking then if we still want this then, or if we maybe want to point people to the archived versions page (and call it previous versions). You can't get older versions from the release notes page either.

**Comment by trav90** [comment]
I've had plans to get an archived versions page up, but haven't had a chance yet. It is on my to do list.

**Comment by squarefractal** [comment]
[**@wolfbeast**](https://github.com/wolfbeast) commented on [Monday, September 28, 2015 12:32:54 AM](https://github.com/MoonchildProductions/PM4Linux-installer/pull/17#issuecomment-143587819 "2015-09-27T19:02:54Z - Replied by Github Comment Enhancer"):
> You can't get older versions from the release notes page either.

The "Show versions" button isn't meant for downloading older releases, it's meant to allow the user to see a list of previous versions, which they can enter into the version selection dialog (which otherwise only contains a single choice, "Latest version").

**Comment by trav90** [comment]
I got a working archived versions page up on the PM4Linux site today.

Closing as this is now solved by commit 9f718d5 (and will be included in the 0.2.1 release).

**Pull request closed without merging**
