### PR TITLE
Display warning regarding gtk2-engines-oxygen crashes.

### PR DESCRIPTION
**Pull request by squarefractal**
With this, can we have a new release of the installer?

### CODE REVIEW

**Comment by wolfbeast** [comment]
Can you let me know what exactly this PR does before I merge it?

**Comment by squarefractal** [comment]
This PR adds a new function `display_install_hints`, that is invoked upon completion of the installation procedure. The function checks for the string "palemoon" in the gtk2-engines-oxygen library to see if support has been added for Pale Moon, and if not, tells the user to upgrade the package and/or use a different theming engine.

**Comment by wolfbeast** [comment]
Wouldn't it be better and cleaner (and proper) to check the lib version for a version range that accepts Pale Moon instead of doing a hard check in the binary if it happens to include the string? Your solution is extremely hack-y, and I definitely don't like it.

**Comment by squarefractal** [comment]
[**@wolfbeast**](https://github.com/wolfbeast) commented on [Monday, September 28, 2015 12:34:38 AM](https://github.com/MoonchildProductions/PM4Linux-installer/pull/16#issuecomment-143587889 "2015-09-27T19:04:38Z - Replied by Github Comment Enhancer"):
> Wouldn't it be better and cleaner (and proper) to check the lib version for a version range that accepts Pale Moon instead of doing a hard check in the binary if it happens to include the string?

You can't just "check the lib version" -- different distros use different package managers and differently named packages (for example, this package is also known as "oxygen-gtk" and "gtk-engines-oxygen"). Moreover, just because the package version is less than x.y.z does not automatically mean that it's bad -- downstream developers will often port a patch for a newer version to the version in their repo, and update a package suffix (Redhat does this all the time, and for very good reasons).

This does not even cover those distributions where the "packages" are compressed archives loaded at boot (Porteus and Puppy Linux), and consequently have no concept of version numbers.

However, I'll add a further check to make Pale Moon support detection more robust, but no less hack-y than it is at present :wink:

**Comment by wolfbeast** [comment]
Hmm.. I see. Well, that's just annoying as f*** :disappointed:

I guess this is as good as it gets then - hack-y as it may be. If you can somehow improve upon it, that would be great!

**Comment by squarefractal** [comment]
The detection mechanism indeed has one drawback -- *if* the KDE developers do get around to do something better than how things currently are and get around to remove application names, then it would erroneously complain about an "older version" without support for Pale Moon.

It could potentially be resolved by checking if similar XUL-based applications such as Firefox/Seamonkey are included in the binary as well. If you do think that this is an acceptable resolution, please let me know, or you can merge the PR as-is.

**Comment by wolfbeast** [comment]
I'll just merge it as-is and we can always see about changing it again if it's needed. If you could keep an eye on the developments there that would be awesome!

**Comment by wolfbeast** [comment]
@trav90 Maybe you can kick off a build and update at this point?

**Comment by trav90** [comment]
Sure thing! I'll have a release ready tonight.

@squarefractal, just curious which distro's you have tested this with?

**Comment by squarefractal** [comment]
[**@trav90**](https://github.com/trav90) commented on [Tuesday, September 29, 2015 1:52:48 AM](https://github.com/MoonchildProductions/PM4Linux-installer/pull/16#issuecomment-143863734 "2015-09-28T20:22:48Z - Replied by Github Comment Enhancer"):
> just curious which distro's you have tested this with?

Sorry for the delay in reply; I have tested it with Kubuntu 14.04.

**Pull request merged**
