### PR TITLE
Clean up residual /opt/palemoon.temp dir when updating.

### PR DESCRIPTION
**Pull request by squarefractal**

### CODE REVIEW

**Comment by squarefractal** [comment]
Is this on the hold for some reason?

**Comment by wolfbeast** [comment]
I've been meaning to get to this, and I could swear I left a comment, but apparently not.
I'm not entirely sure why /opt/palemoon.temp is used to begin with instead of /tmp where this isn't even an issue. Can you explain that to me?
Ping @trav90 
What do you think, can it be rewritten to use /tmp?

**Comment by trav90** [comment]
Using /tmp sounds good to me. I'll have a closer look this week and see what I can come up with.

**Comment by squarefractal** [comment]
[**@wolfbeast**](https://github.com/wolfbeast) commented on [Tue 23 Jun 2015 07:10:20 AM UTC](https://github.com/MoonchildProductions/PM4Linux-installer/pull/11#issuecomment-114386601 "2015-06-23T07:10:20Z - Replied by Github Comment Enhancer"):
> I'm not entirely sure why /opt/palemoon.temp is used to begin with instead of /tmp where this isn't even an issue.

Maybe because `/tmp` can be on a different mount where space is much more limited?

**Comment by wolfbeast** [comment]
Seriously? I think if you don't even have 50MB free on /tmp then you have bigger issues than not being able to upgrade Pale Moon.

**Comment by wolfbeast** [comment]
Opened issue #11 for the follow-up for this.

**Pull request merged**
